# Generated by Django 4.0.4 on 2022-06-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('user_and_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateStartContract', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('DateEndContract', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('Driver', models.BooleanField(blank=True, null=True, verbose_name='Need a driver')),
                ('Note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('Status', models.IntegerField(blank=True, null=True, verbose_name='Order status')),
                ('Comission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Commission')),
                ('Cost', models.IntegerField(blank=True, null=True, verbose_name='Cost')),
                ('DateDel', models.DateField(blank=True, null=True, verbose_name='Delete date')),
                ('Car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='cars.car', verbose_name='Car')),
                ('Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('Date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('Status', models.BooleanField(blank=True, null=True, verbose_name='Status')),
                ('Contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contract', verbose_name='Order')),
                ('From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Send')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
