# Generated by Django 4.0.4 on 2022-06-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        ('user_and_company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackAndComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('Message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('Status', models.BooleanField(blank=True, null=True, verbose_name='Feedback message status')),
                ('Type', models.BooleanField(blank=True, null=True, verbose_name='Message type')),
                ('PhoneEmail', models.CharField(default='', max_length=12, verbose_name='Phone or email')),
                ('DateDel', models.DateField(blank=True, null=True, verbose_name='Delete date')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('Contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contract', verbose_name='Order')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Admin or employee')),
            ],
            options={
                'verbose_name': 'Comment or message',
                'verbose_name_plural': 'Comments or messages',
                'ordering': ['-id'],
            },
        ),
    ]
