# Generated by Django 4.0.4 on 2022-06-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_and_company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCat', models.CharField(max_length=100, verbose_name='Name')),
                ('Icon', models.ImageField(upload_to='img_category', verbose_name='Icon')),
                ('DateDel', models.DateField(verbose_name='Delete date')),
                ('Percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percent')),
                ('FixedRate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='FixedRate')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('Photos', models.JSONField(verbose_name='')),
                ('RentCondition', models.TextField(blank=True, null=True, verbose_name='RentCondition')),
                ('Header', models.CharField(blank=True, max_length=150, null=True, verbose_name='Header')),
                ('Driver', models.BooleanField(blank=True, null=True, verbose_name='Driver')),
                ('Status', models.BooleanField(blank=True, null=True, verbose_name='Status')),
                ('CategoryVU', models.CharField(blank=True, max_length=250, null=True, verbose_name='CategoryVUID')),
                ('DateDel', models.DateField(blank=True, null=True, verbose_name='Delete date')),
                ('FixedRate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='FixedRate')),
                ('Percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percent')),
                ('Brand_and_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Brand_and_name')),
                ('Transmission', models.IntegerField(blank=True, choices=[(0, 'Manual'), (1, 'Auto')], default=0, null=True, verbose_name='Transmission')),
                ('Engine', models.IntegerField(blank=True, choices=[(0, 'Petrol '), (1, 'Diesel')], default=0, null=True, verbose_name='Engine')),
                ('Car_type', models.IntegerField(blank=True, choices=[(0, 'Sedan'), (1, 'Crossover'), (2, 'Universal'), (3, 'Hatchback'), (4, 'Coupe'), (5, 'Micro')], default=0, null=True, verbose_name='Car_type')),
                ('Drive', models.IntegerField(blank=True, choices=[(0, 'Full'), (1, 'Back'), (2, 'Front')], default=0, null=True, verbose_name='Drive ')),
                ('Wheel_drive', models.IntegerField(blank=True, choices=[(0, 'Right'), (1, 'Left')], default=0, null=True, verbose_name='Wheel_drive')),
                ('Year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('Power', models.IntegerField(blank=True, null=True, verbose_name='Power')),
                ('Price', models.IntegerField(blank=True, null=True, verbose_name='Cost')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.category', verbose_name='Category')),
                ('CompanyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.company', verbose_name='ID Company')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
